### ISSUE TITLE
Runtime unreachable

### ISSUE THREAD

**Issue by selwyn-mccracken** [mithril-security/tokenizers-wasm#1]
Hi,

Thanks for the good work - I've been watching eagerly your progress on getting wasm tokenizers working (as well as  #huggingface/tokenizers/pull/1009)

However, I get a runtime unreachable error when I try and run your example, with both a local tokenizer.json file and when trying to use the load button with a tokeninzer name (e.g.    sentence-transformers/bert-base-nli-mean-tokens)

![image](https://user-images.githubusercontent.com/911012/173327469-a0dccfe4-0853-46e4-b4d1-4bdfc1a4dce3.png)

I'm interested in your example, as you're reading in an external json file, whereas the [new unstable_wasm example]( https://github.com/huggingface/tokenizers/blob/main/tokenizers/examples/unstable_wasm/src/lib.rs) creates the tokeniser at build time, and I haven't had much success modifying it to load in an external file with it.

(Although for simplicity, I'd prefer just to bake in the relevant file at build time - the below works as a normal binary, but I get the same unreachable error as above when run from wasm) 

```
static VOCAB: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/sentence-transformers-all-mpnet-base-v2-tokenizer.json"));

#[wasm_bindgen]
pub fn tokenize(text: &str) -> Vec<u32> {
    let tokenizer: Tokenizer = Tokenizer::from_str(VOCAB).unwrap().into();
    tokenizer 
        .encode(text, false)
        .unwrap()
        .get_ids()
        .into_iter()
        .cloned()
        .collect()
}

```

Let me know if there is any further info you'd like to help debug?

**Comment by mbrunel** [comment]
Hello, sorry for the very late response (I never thought someone would find this repo) and thank you for your interest in this.

I'm not exactly sure as to what happened to you, but it might have just been broken for a bit, since all of this is very new. I pushed both tokenizers-wasm and huggingface-tokenizers-bindings to npm, so it should be more straightforward to use. If you have the time, could you test the new simplified example and tell me if you still have the same problems, it would be very helpfull.

Best of luck to you!

**Comment by selwyn-mccracken** [comment]
Thanks for the update, npm packages and the simplified example. 

The example works, but I still get an issue with some model names, which I think is due to the inconsistencies of huggingfaces url resolver when you try to fetch a model with a nested name via
```return fetch(`https://huggingface.co/${name}/resolve/main/tokenizer.json`)```

So "sentence-transformers/paraphrase-MiniLM-L6-v2" works but "sentence-transformers/all-mpnet-base-v2" does not, and tokenizer.json exists in both model locations.

I've no idea why, but I'll close the issue, as I can modify your example with a specified url.
